# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = TrigMuonEfficiency
PACKAGE_PRELOAD  = RIO
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = 
PACKAGE_DEP      = egammaAnalysisUtils
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common
